# Generated by Django 2.2b1 on 2019-02-28 21:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('card_title', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('card_type', models.TextField(blank=True, null=True)),
                ('front_image', models.TextField(blank=True, null=True)),
                ('card_text', models.TextField(blank=True, null=True)),
                ('traits', models.TextField(blank=True, null=True)),
                ('amber', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('rarity', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('expansion', models.IntegerField(blank=True, null=True)),
                ('is_maverick', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Current_Page',
            fields=[
                ('page', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('run_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('expansion', models.IntegerField(blank=True, null=True)),
                ('power_level', models.IntegerField(blank=True, null=True)),
                ('chains', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('num_action', models.IntegerField(blank=True, null=True)),
                ('num_artifact', models.IntegerField(blank=True, null=True)),
                ('num_creature', models.IntegerField(blank=True, null=True)),
                ('num_upgrade', models.IntegerField(blank=True, null=True)),
                ('bonus_amber', models.IntegerField(blank=True, null=True)),
                ('creature_pwr', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'deck_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck_House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deck_house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck2',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('expansion', models.IntegerField(blank=True, null=True)),
                ('power_level', models.IntegerField(blank=True, null=True)),
                ('chains', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('num_action', models.IntegerField(blank=True, null=True)),
                ('num_artifact', models.IntegerField(blank=True, null=True)),
                ('num_creature', models.IntegerField(blank=True, null=True)),
                ('num_upgrade', models.IntegerField(blank=True, null=True)),
                ('bonus_amber', models.IntegerField(blank=True, null=True)),
                ('creature_pwr', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('house_list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('card_list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'deck2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('artifact', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('creature', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('upgrade', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amber', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distribution',
                'managed': True,
            },
        ),
    ]
