# Generated by Django 2.2b1 on 2019-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0002_auto_20190228_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
