# Generated by Django 2.2b1 on 2019-02-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0003_auto_20190228_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
