# Generated by Django 2.1.7 on 2019-02-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'managed': True},
        ),
    ]
