# Generated by Django 2.1.7 on 2019-02-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0002_auto_20190220_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='bonus_amber',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='creature_pwr',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='num_action',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='num_artifact',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='num_creature',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='num_upgrade',
        ),
    ]
