# Generated by Django 2.1.7 on 2019-02-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0003_auto_20190220_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='bonus_amber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='creature_pwr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='num_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='num_artifact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='num_creature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='num_upgrade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
