# Generated by Django 2.1.7 on 2019-02-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0004_auto_20190220_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='creature_pwr',
        ),
    ]
