# Generated by Django 2.1.7 on 2019-02-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_main', '0006_deck_creature_pwr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'managed': False},
        ),
    ]
